---
title: Documenting your code
hero_image: images/banner.png
description: Learn how to document Python code and create websites for software projects
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-3
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: Getting started
- title: Documenting your code
  completion:
  - engaged
- title: Generating documentation
- title: Challenge
- title: Create a project website
- title: Build your website
- title: Adding your code
- title: Creating pages
  completion:
  - internal
- title: 'Challenge: improve your website'
