title: Documenting your code
hero_image: images/banner.png
description: A project which shows how to document Python code
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: developer, design-0, programming-4, phys-comp-0, manufacture-0, community-3
interests: "animals, big-project, art and design, jokes/pranks, space, photography, nature/outside/weather, music/sound, physical computing, games, robots, geography"
technologies: "python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Getting Started
  - title: Documenting your code
  - title: Generating documentation
  - title: Challenge
  - title: Create a project website
  - title: Adding your code
  - title: Creating pages
  - title: What next?